### ISSUE TITLE
Does not seem to replicate pre-2008 benchmarks game repo ?

### ISSUE THREAD

**Issue by igouy** [Byron/benchmarksgame-cvs-mirror-pre-2008#1]
The CVS repo provides access to multiple versions of programs, this mirror repo only seems to provide the latest versions?

So compared to CVS shootout/bench/ackermann this mirror repo seems to have about 74 but is missing the 27 deleted and about 82 changed that are still available in CVS.

Is that correct?

**Comment by Byron** [comment]
The repository just uses the standard git-cvs importer, which may have some shortcomings.
Maybe it is related to CVS just containing the history till 2005, or at least this is all it imports into git - 3 years seem to be missing?

**Comment by igouy** [comment]
> CVS just containing the history till 2005

No.

For example: ackermann.ifc dated [Tue Dec 4 06:32:37 2007](https://alioth.debian.org/scm/viewvc.php/shootout/bench/ackermann/ackermann.ifc?root=shootout&view=log)

> standard git-cvs importer

Someone else seems to have [a mirror archive that has the 2007 ackermann.ifc](https://github.com/kragen/shootout/blob/master/bench/ackermann/ackermann.ifc)

**Comment by Byron** [comment]
Perfect, this means my mirror is actually not required, and I could link mine to the one you found, or close it down completely.
What do you recommend?

**Comment by igouy** [comment]
> What do you recommend?


If it was me, I'd want to figure out why the import didn't work.

If you don't want the mirror repo then delete it.

**Comment by Byron** [comment]
Great, thanks! I will just delete it then.
